### ISSUE TITLE
Change translation for genders

### ISSUE THREAD

**Issue by kiriikp** [Ruin0x11/ElonaPlusCustom_GX#24]
Stock plus:
Male?
Female?
Bisexual

CGX:
trans-male
trans-female
hermaphrodite

I don't particularly like either bisexual or hermaphrodite, but otherwise the terms used in stock plus are just a lot more versatile, letting you play a character who is simply crossdressing, for instance, while the terms used in CGX explicitly state the character is transgender.

**Comment by Ruin0x11** [comment]
Maybe we could do this:

1. Revert the gender translations to stock Plus.
2. Add a new option in the character creation process for renaming the current gender to any arbitrary name.
3. Change the logic for the current `sex` wish to offer the same selection/renaming ability as in character creation, instead of just changing between male/female.

Does this sound reasonable? I'd want to be careful to ensure that everyone can play the gender they'd want. (Although there are some cases like Forbidden Meat that cause the same gender changing effect where I'm not sure what sort of solution is most desirable.)

**Comment by kiriikp** [comment]
Personally I'm fine with the stock plus options, male? and female? are ambiguous enough to mean anything you want them to, which is all I'm really looking for, plus you've got "unknown" as an option
Making the sex wish bring up the character creation menu would be a nice change.
I'm not really sure how custom genders would work, would NPCs with that gender also show the custom term?

**Comment by Ruin0x11** [comment]
The custom genders would be the same as race/class renaming already in stock plus. It would be a name change for your selected gender for roleplaying purposes. To clarify, there is a `sex` field on each character for male/female/other, and there is also a `newsex` field containing the name of the gender to display, which can be anything.

**Comment by kiriikp** [comment]
Ah, I didn't realise the functionality was already there. In that case it makes sense.

**Comment by Ruin0x11** [comment]
The proposed changes are now a part of 2.07.2.0. Some of the code will still check for characters using the old translations of the genders for backwards compatibility, but the genders for new characters will use stock Plus' translations from now on.
