### ISSUE TITLE
Still getting crashes on resolution changes.

### ISSUE THREAD

**Issue by blazer30** [Ruin0x11/ElonaPlusCustom_GX#29]
I don't know how to reopen the closed thread so I made another.
I am still getting the same crashes on the larger resolution options and even changing the DPI for them.

**Comment by Ruin0x11** [comment]
My bad. I am tracking what appears to be the same issue at #21. Please see there for more information.

The problem is caused by selecting a resolution that is larger than the total size of your display. Could you make sure that there are no parts of the game window that are cut off when loading a save?

I am working on fixing this by limiting the list of valid screen resolutions.

**Comment by Ruin0x11** [comment]
I fixed some additional issues with the DPI scaling in 2.07.2.0. If crashes still happen then do reopen this issue.
