### ISSUE TITLE
The top row of tiles are partially outside view window depending on window height

### ISSUE THREAD

**Issue by jacklinzoho** [Ruin0x11/ElonaPlusCustom_GX#47]
This is a bug in the base Elona game - would it be possible to fix it in cgx?

Right now I'm using windowH=1048, but if I increase it further the top row of tiles becomes progressively outside the view window, until at 1096 it becomes inside again and the cycle restarts.

**Comment by firecat6666** [comment]
In windowed mode, if you make windowH a multiple of 48 then increase that value by 43 you get the minimum cropping. One pixel over that and it cuts off the top tiles. I don't know if it's the same value for fullscreen.
There's a similar problem with the rightmost tiles but it's not as noticeable because the value with the least cropping is just a multiple of 48 plus 3, and the game will actually display the entire tiles, unlike with the topmost tiles.
I'm not sure if anyone knows how to fix it, seeing as how this was never fixed in E+, but a bandaid fix would be to have the default resolution options have these ugly values instead of the pretty, round ones.

**Comment by jacklinzoho** [comment]
The formula is 48x+40, since anything that's not a multiple of 4 is rounded down to the nearest multiple of 4.  So in my case, I guess 1048 is the best I can do (windowed mode, a bit smaller than 1080 to account for the window title bar).  It's a shame, though, because it leaves a 4-pixel tall band at the bottom of the window.  1052 would have covered up the screen completely.

**Comment by firecat6666** [comment]
Oh, I didn't know about the rounding down thing. I don't know if this can help you, but you can set windowY to a negative value and the game will start with the window partially outside of the screen. There's a specific value that will leave the entire title bar outside the screen but none of the game itself, for me it's -23 (I leave it at -20 so there's still a sliver of the title bar visible so I can grab it in case I want to move the window around).

**Comment by Ruin0x11** [comment]
So I tried to fix this, and it turns out it's much harder than it seems. Here's why: While in-game, if you look at where the message window at the bottom of the screen and the tile grid intersect, you'll notice that the bottom of the tiles align perfectly with the top of the message window. This is very much intentional, because the message window doesn't actually draw over the tiles; in fact, the tiles have the potential to draw over the message window during rendering unless more steps are taken.

And, as it turns out, when the screen scrolls there is a hack in the scrolling code that copies the top half of the message window, draws the tiles, and then pastes the copied message window back over itself to cover up any tiles that scrolled into the window. Here is the actual code for the curious:

https://github.com/Ruin0x11/ElonaPlusCustom-GX/blob/1da105e13445e0a2f921384f157ec5c023071943/2.05-custom-gx/screen.hsp#L4913-L4922

All the rest of the code assumes that the tiles are perfectly flush with the message window. So breaking this assumption means I'd have to do a ridiculous number of hacks in the tile renderer to render only half of a tile/character/item if the player is near the top of the screen. An alternative is to do the message window saving/restoring every time the screen is refreshed, but that could slow down the renderer a lot.

So instead of trying to make the tiles that get cut off flush with the top of the screen, I'll probably fix this by simply increasing the tile draw bounds on the Y axis if a fractional resolution is being used. This means there will be a small gap at the top depending on your screen resolution, but it would at least allow you to see the entire row of tiles.

**Comment by firecat6666** [comment]
Sorry, I don't know how to code so I don't know what that code means or how hard it is to fix this. But seeing how this issue has been around since always and from reading comments about people trying to mod Elona over the years I imagine the game code is just this gigantic bowl of spaghetti and nothing will ever be easy to fix/change unless all you have to do is change a single word or letter or number somewhere.

But for your consideration, here's an idea I had (which may or may not be good/easy to implement): If the window size isn't one such that the entire tiles can be displayed on the top row/right column, then have the game simply not render that row/column, perhaps by making the game think the resolution is smaller than what it is. In other words, make the game show an empty row/column (maybe just empty black space) instead of partially showing that row/column. Though from what you said I'm guessing the issue with the top row is different from the issue with the right column, so maybe a general solution like this won't work for both.

**Comment by Ruin0x11** [comment]
So as a compromise, I added a new config option in 2.08.1.0 named `showTopTileCutoff.` which will fully show the top row. The tiles outside the map boundaries will appear as the default fog tiles, but at least you can now see the rest of the map.
