### ISSUE TITLE
Spell strength in casting menu might not scale with spell level

### ISSUE THREAD

**Issue by Ruin0x11** [Ruin0x11/ElonaPlusCustom_GX#48]

**Comment by firecat6666** [comment]
If you mean the dice numbers for spells and other such things in the Spell and Character windows, they do scale with spell level and stats, but not with spellpower. I tested this by looking at Heal Light numbers and casting Divine Wisdom to boost my intelligence, which boosts spellpower and intelligence spells but not wisdom spells, no change. Equipping/unequipping Mag-Abyss, also no change. But increasing spell level, increasing my wisdom via casting Concentration or equipping 5 stones (7 will each) on my hands/shoot, all changed the numbers.

But this is how it works in non-Custom, and I think has worked since... always? Or at least since equips that enhance spells were introducing, I don't remember if this attribute existed in vanilla.

**Comment by Ruin0x11** [comment]
I'll close this for the time being, as it seems to be intended behavior. If not, then please reopen.
