### ISSUE TITLE
feature request: auto-drop opened chests

### ISSUE THREAD

**Issue by jacklinzoho** [Ruin0x11/ElonaPlusCustom_GX#50]
When the PC opens a treasure chest (jeweled chest, gatcha capsule, etc) in inventory, it should by default drop the empty.  This saves having to drop it manually.

I think it makes sense because in the vast majority of cases you'd drop it manually afterwards anyway.  In the rare occasion when you want to take the empties it isn't too much of a burden to pick it back up.

**Comment by firecat6666** [comment]
Put the empty ones in your shop, there's a chance they'll get exchanged for unopened containers. Even crappy gamble chests can be exchanged for safes, chests and the like. Although, empty gamble chests level 12 and below and (empty) empty wallets never get sold for some reason. I'm not sure if the unopened ones get sold. There are also some fusion recipes that use containers, either any type of container or material box specifically.

If I don't want the container (usually safe/chest because they're heavy) I'll just open it while it's on the ground and only pick up the contents. Otherwise I bring them with me and sell them to a vendor together with all the other junk I pick up. Containers all get grouped together in the inventory so it's not a problem to drop/sell all of them in one go, just hold spacebar/enter/whatever until they're all gone.

**Comment by jacklinzoho** [comment]
Even when you're selling it in the shop you'd still want to bring it unopened and open it in the shop, since this way they stack.  This means autodrop is still more convenient.

**Comment by firecat6666** [comment]
I'm not sure if opening them in the shop makes any difference. I almost always open the containers I get from shop sales inside the shops (since I'll be dropping them there anyway), I always drop them in the same pile and I don't think I've ever seen them stacking naturally, they always remain in the pile as individual items (even ones with the same type and colour).

In any case, it's best to use the stack items hotkey (I think the default is 'I') if you want to stack opened containers. Although I'm not quite sure what the criteria all are that the game uses to decide when trying to stack chests when using that key, I know opened gamble chests of the same level (at least if they were all bought from a vendor) and opened bejeweled chests from defeating a random dungeon boss (if the chests are the same colour) will all stack when using the stack items hotkey, even if they're not stacking in your inventory or when dropped on the same tile. On the other hand, I can almost never stack opened material boxes.

One idea I had regarding this was to make the stack items hotkey stack all opened containers of the same type (and colour) regardless of everything else but it seems containers all have a hidden difficulty level (visible on gamble chests), and I'm pretty sure this level is conserved when the container is exchanged in the shop, as I've gotten containers that were (almost) too difficult for me to open after finding such containers in dungeons and putting them for sale. I don't know if this has any implications for the contents of the containers that you get from shop exchanges, but it sure would have been nice if I could stack those opened material boxes so I could start collecting them in large numbers.

**Comment by Ruin0x11** [comment]
Added in 2.10.1.0.
