### ISSUE TITLE
(non-Custom) Having platinum pieces increases monster evasion

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#53]
I'm not entirely sure this is a bug but it's really weird and I haven't read anything about it in changelogs.

This issue can be easily observed by using Data Scan special action. With 0 (or negative) platinum the game displays a certain number for monster evasion. Then with 1 to 9 platinum the number is a bit higher, and it increases again at 20, 30, 40, etc platinum. At extremely high platinum numbers (like way over a billion) the evasion can overflow and depending on the monster and how much platinum you have, it can become 1 or negative or the [HITx] [EVAx] message stops appearing altogether. I should note that this isn't just cosmetic, the game does behave as if the monster has the evasion number displayed as far as I could tell, though I don't know what the behaviour should be in the case of negative evasion or when the message disappears.

While this isn't really a noticeable problem in most normal game situations, it can be problematic if the player decides to hoard platinum up to the 100 cap in the early game, as it does give a relatively sizeable increase in evasion to monsters with very low evasion (for example, a wild rabbit found in the wilderness goes from [EVA78] with 0pp to [EVA168] with 100pp). It's also VERY noticeable in easy game modes (where there's no pp cap) if the player is hoarding thousands of platinum. It's also problematic for cheaters like me who like to have millions of platinum at all times for convenience.

But as I said at the start, I don't know if this is actually a bug. Maybe it's part of the changes that Ano made to force people to stop hoarding platinum, but if that's the case, then this one is missing from changelogs, unlike the other changes. I tested this in 1.76, there's no Data Scan there but when the monster's evade in in the hundreds of millions it's very easy to see that you're missing all non-critical attacks and I couldn't observe this issue there.

**Comment by Ruin0x11** [comment]
As far as I understand, this was an intentional change. It was added sometime in the gap between 1.90 and 2.05, but I'm not exactly sure when.

Here is the relevant code:

https://github.com/Ruin0x11/ElonaPlusCustom-GX/blob/c68a7bcc4f20c97aca40ef875fb2372d2e471729/2.05-custom-gx/screen.hsp#L5850-L5857

**Comment by Ruin0x11** [comment]
So after reading over this a bit more, I think I understand what might have happened. It seems that Ano reused the `cdata` slot for the platinum count and shared it with the Analysis counter introduced in 1.995. This makes sense since a higher Analysis counter is supposed to increase evasion. I think the reuse was because there weren't any more `cdata` slots available and the platinum count on NPCs was unused before.

However, it seems like this is accidentally being applied to the player for some reason.

**Comment by firecat6666** [comment]
Seems like a good way to fix this would be to add an extra condition to this function that checks the ID (offset 108 in cdata) of the attacking entity, if it's the player's ID then the entire thing is skipped. Only the player character can have platinum and no character can have an ID of 0 other than the player, except maybe in case of bugs, so I guess this should work fine 100% of the time.

**Comment by Ruin0x11** [comment]
Should be fixed in 2.10.1.0.
