### ISSUE TITLE
"Display Pickpocket shortcut" tweak doesn't work in Party Time!

### ISSUE THREAD

**Issue by firecat6666** [Ruin0x11/ElonaPlusCustom_GX#57]
Even though the various furniture items there can be stolen. It works everywhere else I can think of. Or rather, that's the only place I've been where I noticed it doesn't work (other than Panic and Challenge quest maps).

**Comment by Ruin0x11** [comment]
According to Anna/Bloodyshade's notes, this was apparently intentional behavior. For the Panic and Challenge maps there's no stealing allowed, but this doesn't seem to apply to Party Time!. I guess if the items can be stolen then there's no reason to disable the shortcut there.

https://github.com/Ruin0x11/ElonaPlusCustom-GX/blob/ec659d9fae8d006b8a965ae5723030d763690a28/2.05-custom-gx/command.hsp#L10830-L10837

**Comment by Ruin0x11** [comment]
Fixed in 2.08.1.0.
